# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDist <- function(lon1, lat1, lon2, lat2) {
    .Call('_RSpatial_getDist', PACKAGE = 'RSpatial', lon1, lat1, lon2, lat2)
}

poThin <- function(df, spacing, dimension, lon, lat) {
    .Call('_RSpatial_poThin', PACKAGE = 'RSpatial', df, spacing, dimension, lon, lat)
}

