# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.classifySpatiallyByBlocks <- function(df, lon, lat, size, blockSize) {
    .Call('_RSpatial_classifySpatiallyByBlocks', PACKAGE = 'RSpatial', df, lon, lat, size, blockSize)
}

.isInsideConvexHull <- function(hulls, checkx, checky, size) {
    .Call('_RSpatial_isInsideConvexHull', PACKAGE = 'RSpatial', hulls, checkx, checky, size)
}

.getAVN <- function(value, lon, lat, values, size) {
    .Call('_RSpatial_getAVN', PACKAGE = 'RSpatial', value, lon, lat, values, size)
}

.mutateNumber <- function(one, two) {
    .Call('_RSpatial_mutateNumber', PACKAGE = 'RSpatial', one, two)
}

.createNextGen <- function(df, avnValues, mutationRate, explore, size, randoms) {
    .Call('_RSpatial_createNextGen', PACKAGE = 'RSpatial', df, avnValues, mutationRate, explore, size, randoms)
}

.getDist <- function(lon1, lat1, lon2, lat2) {
    .Call('_RSpatial_getDist', PACKAGE = 'RSpatial', lon1, lat1, lon2, lat2)
}

.poThin <- function(df, spacing, dimension, lon, lat) {
    .Call('_RSpatial_poThin', PACKAGE = 'RSpatial', df, spacing, dimension, lon, lat)
}

.rasterMaker <- function(df, minX, maxY, nCols, nRows, sizeOfGen, sizeOfList, degree, block) {
    .Call('_RSpatial_rasterMaker', PACKAGE = 'RSpatial', df, minX, maxY, nCols, nRows, sizeOfGen, sizeOfList, degree, block)
}

.rasterMakerAdjust <- function(df, minX, maxY, nCols, nRows, sizeOfGen, sizeOfList, degree, block, horizontal, vertical) {
    .Call('_RSpatial_rasterMakerAdjust', PACKAGE = 'RSpatial', df, minX, maxY, nCols, nRows, sizeOfGen, sizeOfList, degree, block, horizontal, vertical)
}

